spring.application.name=media-service

# Local storage directory
media.storage.dir=./data/media

# --- Server Port ---
server.port=8083

# --- Database ---
spring.datasource.url=jdbc:sqlserver://demoservereca.database.windows.net:1433;database=demoDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=pathumck
spring.datasource.password=aaa%IJSE
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- JPA / Hibernate ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
